## Operaciones Escalares

In [1]:
import dask.array as da

In [2]:
my_arr = da.random.randint(10, size=20, chunks=3)

In [3]:
my_arr.compute()

array([4, 2, 4, 4, 2, 4, 3, 0, 1, 9, 5, 4, 3, 2, 7, 3, 1, 4, 0, 8])

In [4]:
my_hundred_arr = my_arr + 100
my_hundred_arr.compute()

array([104, 102, 104, 104, 102, 104, 103, 100, 101, 109, 105, 104, 103,
       102, 107, 103, 101, 104, 100, 108])

In [5]:
(my_arr * (-1)).compute()

array([-4, -2, -4, -4, -2, -4, -3,  0, -1, -9, -5, -4, -3, -2, -7, -3, -1,
       -4,  0, -8])

## Reducciones / Agregaciones

In [6]:
dask_sum = my_arr.sum()
dask_sum

dask.array<sum-aggregate, shape=(), dtype=int64, chunksize=(), chunktype=numpy.ndarray>

In [7]:
my_arr.compute()

array([4, 2, 4, 4, 2, 4, 3, 0, 1, 9, 5, 4, 3, 2, 7, 3, 1, 4, 0, 8])

In [8]:
dask_sum.compute()

70

In [9]:
my_ones_arr = da.ones((10,10), chunks=2, dtype=int)

In [10]:
my_ones_arr.compute()

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [11]:
my_ones_arr.mean(axis=0).compute()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
my_custom_array = da.random.randint(10, size=(4,4), chunks=(1,4))

In [13]:
my_custom_array.compute()

array([[8, 0, 8, 5],
       [6, 7, 4, 7],
       [1, 6, 3, 0],
       [3, 6, 7, 3]])

In [14]:
my_custom_array.mean(axis=0).compute()

array([4.5 , 4.75, 5.5 , 3.75])

In [15]:
my_custom_array.mean(axis=1).compute()

array([5.25, 6.  , 2.5 , 4.75])

## Slicing

In [16]:
my_custom_array[1:3, 2:4]

dask.array<getitem, shape=(2, 2), dtype=int64, chunksize=(1, 2), chunktype=numpy.ndarray>

In [17]:
my_custom_array[1:3, 2:4].compute()

array([[4, 7],
       [3, 0]])

## Broadcasting

In [18]:
my_custom_array.compute()

array([[8, 0, 8, 5],
       [6, 7, 4, 7],
       [1, 6, 3, 0],
       [3, 6, 7, 3]])

In [19]:
my_small_arr = da.ones(4, chunks=2)
my_small_arr.compute()

array([1., 1., 1., 1.])

In [20]:
brd_example1 = da.add(my_custom_array, my_small_arr)

In [21]:
# [[7, 1, 4, 4], + [[1, 1, 1, 1]
#  [1, 5, 5, 5],   [1, 1, 1, 1]
#  [9, 0, 2, 8],   [1, 1, 1, 1]
#  [1, 8, 8, 0]]   [1, 1, 1, 1]]
brd_example1.compute()

array([[9., 1., 9., 6.],
       [7., 8., 5., 8.],
       [2., 7., 4., 1.],
       [4., 7., 8., 4.]])

In [22]:
ten_arr = da.full_like(my_small_arr, 10)

In [23]:
ten_arr.compute()

array([10., 10., 10., 10.])

In [24]:
brd_example2 = da.add(my_custom_array, ten_arr)

In [25]:
brd_example2.compute()

array([[18., 10., 18., 15.],
       [16., 17., 14., 17.],
       [11., 16., 13., 10.],
       [13., 16., 17., 13.]])

## Reshaping

In [26]:
my_custom_array.shape

(4, 4)

In [27]:
custom_arr_1d = my_custom_array.reshape(16)

In [28]:
custom_arr_1d

dask.array<reshape, shape=(16,), dtype=int64, chunksize=(4,), chunktype=numpy.ndarray>

In [29]:
custom_arr_1d.compute()

array([8, 0, 8, 5, 6, 7, 4, 7, 1, 6, 3, 0, 3, 6, 7, 3])

# Stacking

In [30]:
stacked_arr = da.stack([brd_example1, brd_example2])

In [31]:
stacked_arr.compute()

array([[[ 9.,  1.,  9.,  6.],
        [ 7.,  8.,  5.,  8.],
        [ 2.,  7.,  4.,  1.],
        [ 4.,  7.,  8.,  4.]],

       [[18., 10., 18., 15.],
        [16., 17., 14., 17.],
        [11., 16., 13., 10.],
        [13., 16., 17., 13.]]])

In [32]:
another_stacked = da.stack([brd_example1, brd_example2], axis=1)

In [33]:
another_stacked.compute()

array([[[ 9.,  1.,  9.,  6.],
        [18., 10., 18., 15.]],

       [[ 7.,  8.,  5.,  8.],
        [16., 17., 14., 17.]],

       [[ 2.,  7.,  4.,  1.],
        [11., 16., 13., 10.]],

       [[ 4.,  7.,  8.,  4.],
        [13., 16., 17., 13.]]])

# Concatenate

In [ ]:
concate_arr = da.concatenate([brd_example1, brd_example2])

In [ ]:
concate_arr.compute()

array([[ 8.,  2.,  5.,  5.],
       [ 2.,  6.,  6.,  6.],
       [10.,  1.,  3.,  9.],
       [ 2.,  9.,  9.,  1.],
       [17., 11., 14., 14.],
       [11., 15., 15., 15.],
       [19., 10., 12., 18.],
       [11., 18., 18., 10.]])

In [ ]:
another_concate_arr = da.concatenate([brd_example1, brd_example2],axis=1)

In [ ]:
another_concate_arr.compute()

array([[ 8.,  2.,  5.,  5., 17., 11., 14., 14.],
       [ 2.,  6.,  6.,  6., 11., 15., 15., 15.],
       [10.,  1.,  3.,  9., 19., 10., 12., 18.],
       [ 2.,  9.,  9.,  1., 11., 18., 18., 10.]])